### ISSUE TITLE
Misleading documentation on read-only connections

### ISSUE THREAD

**Issue by mertalpt** [canonical/pgbouncer-k8s-operator#148]
## Steps to reproduce
With apologies I will break the format a bit because this is too simple to put many details. For details please check out the [thread](https://chat.charmhub.io/charmhub/pl/p9cbbxhn5tr5pgufcqqr8m3zae) that led to this issue.

## Expected behavior
For connections made to the database name `<db>_standby` to connect to the read-only replicas of a related `postgresql` deployment.

## Actual behavior
PgBouncer pod IP: `10.1.38.152`

```
$ psql -h 10.1.38.152 -p 6432 -d salesforce -U relation_id_6
Password for user relation_id_6: <Input 't3SW2cU5fISuOAWW8RkBOHQ0' -- logs in>
```

```
$ psql -h 10.1.38.152 -p 6432 -d salesforce_standby -U relation_id_6
lation_id_6
Password for user relation_id_6: <Input 't3SW2cU5fISuOAWW8RkBOHQ0' -- fails>
psql: error: connection to server at "10.1.38.152", port 6432 failed: FATAL:  password authentication failed
```

```
$ psql -h 10.1.38.152 -p 6432 -d salesforce_readonly -U relation_id_6
Password for user relation_id_6: <Input 't3SW2cU5fISuOAWW8RkBOHQ0' -- logs in>
```

## Additional context
I believe the fix is to either update the `README` to reflect that the working usage is `<db>_readonly` or to update the code so that the working usage is `<db>_standby`.

**Comment by dragomirp** [comment]
Hi, <db>_readonly is the correct name, updated the readme. Sorry for the delay.
